package de.skyrising.xmpp;

import java.util.Map;
import java.util.TreeMap;

public class XMPP {
    public static final int C2S_PORT = 5222;
    public static final int S2S_PORT = 5269;
    public static final Map<Integer, String> XEP_NAMES = new TreeMap<>();

    public enum StateChange {
        STARTING, STOPPING, RESTARTING, PAUSING, UNPAUSING, ENCRYPTED, STREAM_OPEN, STREAM_CLOSED, AUTHENTICATING, SASL_SUCCESS, RESOURCE_BOUND;
    }

    public static class Namespace {
        public static final String STREAMS = "http://etherx.jabber.org/streams";
        public static final String STANZAS = "urn:ietf:params:xml:ns:xmpp-stanzas";

        public static class Feature {
            public static final String STARTTLS = "urn:ietf:params:xml:ns:xmpp-tls";
            public static final String REGISTER = "http://jabber.org/features/iq-register";
            public static final String SASL = "urn:ietf:params:xml:ns:xmpp-sasl";
            public static final String CSI = "urn:xmpp:csi:0";
            public static final String SM2 = "urn:xmpp:sm:2";
            public static final String SM3 = "urn:xmpp:sm:3";
            public static final String BIND = "urn:ietf:params:xml:ns:xmpp-bind";
            public static final String SESSION = "urn:ietf:params:xml:ns:xmpp-session";
            public static final String ROSTERVER = "urn:xmpp:features:rosterver";
            public static final String COMPRESSION = "http://jabber.org/features/compress";
        }

        public static class IQ {
            public static final String ROSTER = "jabber:iq:roster";
        }
    }

    static {
        XEP_NAMES.put(1, "XMPP Extension Protocols");
        XEP_NAMES.put(2, "Special Interest Groups (SIGs)");
        XEP_NAMES.put(3, "Proxy Accept Socket Service (PASS)");
        XEP_NAMES.put(4, "Data Forms");
        XEP_NAMES.put(5, "Jabber Interest Groups");
        XEP_NAMES.put(6, "Profiles");
        XEP_NAMES.put(7, "Conferencing SIG");
        XEP_NAMES.put(8, "IQ-Based Avatars");
        XEP_NAMES.put(9, "Jabber-RPC");
        XEP_NAMES.put(10, "Whiteboarding SIG");
        XEP_NAMES.put(11, "Jabber Browsing");
        XEP_NAMES.put(12, "Last Activity");
        XEP_NAMES.put(13, "Flexible Offline Message Retrieval");
        XEP_NAMES.put(14, "Message Tone");
        XEP_NAMES.put(15, "Account Transfer");
        XEP_NAMES.put(16, "Privacy Lists");
        XEP_NAMES.put(17, "Naive Packet Framing Protocol");
        XEP_NAMES.put(18, "Invisible Presence");
        XEP_NAMES.put(19, "Streamlining the SIGs");
        XEP_NAMES.put(20, "Feature Negotiation");
        XEP_NAMES.put(21, "Jabber Event Notification Service (ENS)");
        XEP_NAMES.put(22, "Message Events");
        XEP_NAMES.put(23, "Message Expiration");
        XEP_NAMES.put(24, "Publish/Subscribe");
        XEP_NAMES.put(25, "Jabber HTTP Polling");
        XEP_NAMES.put(26, "Internationalization (I18N)");
        XEP_NAMES.put(27, "Current Jabber OpenPGP Usage");
        XEP_NAMES.put(28, "No Such XEP");
        XEP_NAMES.put(29, "Definition of Jabber Identifiers (JIDs)");
        XEP_NAMES.put(30, "Service Discovery");
        XEP_NAMES.put(31, "A Framework For Securing Jabber Conversations");
        XEP_NAMES.put(32, "Jabber URI Scheme");
        XEP_NAMES.put(33, "Extended Stanza Addressing");
        XEP_NAMES.put(34, "SASL Integration");
        XEP_NAMES.put(35, "SSL/TLS Integration");
        XEP_NAMES.put(36, "Pub-Sub Subscriptions");
        XEP_NAMES.put(37, "DSPS - Data Stream Proxy Service");
        XEP_NAMES.put(38, "Icon Styles");
        XEP_NAMES.put(39, "Statistics Gathering");
        XEP_NAMES.put(40, "Jabber Robust Publish-Subscribe");
        XEP_NAMES.put(41, "Reliable Entity Link");
        XEP_NAMES.put(42, "Jabber OOB Broadcast Service (JOBS)");
        XEP_NAMES.put(43, "Jabber Database Access");
        XEP_NAMES.put(44, "Full Namespace Support for XML Streams");
        XEP_NAMES.put(45, "Multi-User Chat");
        XEP_NAMES.put(46, "DTCP");
        XEP_NAMES.put(47, "In-Band Bytestreams");
        XEP_NAMES.put(48, "Bookmarks");
        XEP_NAMES.put(49, "Private XML Storage");
        XEP_NAMES.put(50, "Ad-Hoc Commands");
        XEP_NAMES.put(51, "Connection Transfer");
        XEP_NAMES.put(52, "File Transfer");
        XEP_NAMES.put(53, "XMPP Registrar Function");
        XEP_NAMES.put(54, "vcard-temp");
        XEP_NAMES.put(55, "Jabber Search");
        XEP_NAMES.put(56, "Business Data Interchange");
        XEP_NAMES.put(57, "Extended Roster");
        XEP_NAMES.put(58, "Multi-User Text Editing");
        XEP_NAMES.put(59, "Result Set Management");
        XEP_NAMES.put(60, "Publish-Subscribe");
        XEP_NAMES.put(61, "Shared Notes");
        XEP_NAMES.put(62, "Packet Filtering");
        XEP_NAMES.put(63, "Basic Filtering Operations");
        XEP_NAMES.put(64, "XPath Filtering");
        XEP_NAMES.put(65, "SOCKS5 Bytestreams");
        XEP_NAMES.put(66, "Out of Band Data");
        XEP_NAMES.put(67, "Stock Data Transmission");
        XEP_NAMES.put(68, "Field Standardization for Data Forms");
        XEP_NAMES.put(69, "Compliance SIG");
        XEP_NAMES.put(70, "Verifying HTTP Requests via XMPP");
        XEP_NAMES.put(71, "XHTML-IM");
        XEP_NAMES.put(72, "SOAP Over XMPP");
        XEP_NAMES.put(73, "Basic IM Protocol Suite");
        XEP_NAMES.put(74, "Simple Access Control");
        XEP_NAMES.put(75, "Jabber Object Access Protocol (JOAP)");
        XEP_NAMES.put(76, "Malicious Stanzas");
        XEP_NAMES.put(77, "In-Band Registration");
        XEP_NAMES.put(78, "Non-SASL Authentication");
        XEP_NAMES.put(79, "Advanced Message Processing");
        XEP_NAMES.put(80, "User Location");
        XEP_NAMES.put(81, "Jabber MIME Type");
        XEP_NAMES.put(82, "XMPP Date and Time Profiles");
        XEP_NAMES.put(83, "Nested Roster Groups");
        XEP_NAMES.put(84, "User Avatar");
        XEP_NAMES.put(85, "Chat State Notifications");
        XEP_NAMES.put(86, "Error Condition Mappings");
        XEP_NAMES.put(87, "Stream Initiation");
        XEP_NAMES.put(88, "Client Webtabs");
        XEP_NAMES.put(89, "Generic Alerts");
        XEP_NAMES.put(90, "Legacy Entity Time");
        XEP_NAMES.put(91, "Legacy Delayed Delivery");
        XEP_NAMES.put(92, "Software Version");
        XEP_NAMES.put(93, "Roster Item Exchange");
        XEP_NAMES.put(94, "Agent Information");
        XEP_NAMES.put(95, "Stream Initiation");
        XEP_NAMES.put(96, "SI File Transfer");
        XEP_NAMES.put(97, "iCal Envelope");
        XEP_NAMES.put(98, "Enhanced Private XML Storage");
        XEP_NAMES.put(99, "IQ Query Action Protocol");
        XEP_NAMES.put(100, "Gateway Interaction");
        XEP_NAMES.put(101, "HTTP Authentication using Jabber Tickets");
        XEP_NAMES.put(102, "Security Extensions");
        XEP_NAMES.put(103, "URL Address Information");
        XEP_NAMES.put(104, "HTTP Scheme for URL Data");
        XEP_NAMES.put(105, "Tree Transfer Stream Initiation Profile");
        XEP_NAMES.put(106, "JID Escaping");
        XEP_NAMES.put(107, "User Mood");
        XEP_NAMES.put(108, "User Activity");
        XEP_NAMES.put(109, "Out-of-Office Messages");
        XEP_NAMES.put(110, "Generic Maps");
        XEP_NAMES.put(111, "A Transport for Initiating and Negotiating Sessions (TINS)");
        XEP_NAMES.put(112, "User Physical Location");
        XEP_NAMES.put(113, "Simple Whiteboarding");
        XEP_NAMES.put(114, "Jabber Component Protocol");
        XEP_NAMES.put(115, "Entity Capabilities");
        XEP_NAMES.put(116, "Encrypted Session Negotiation");
        XEP_NAMES.put(117, "Intermediate IM Protocol Suite");
        XEP_NAMES.put(118, "User Tune");
        XEP_NAMES.put(119, "Extended Presence Protocol Suite");
        XEP_NAMES.put(120, "Infobits");
        XEP_NAMES.put(121, "Dublin Core Infobits Mapping");
        XEP_NAMES.put(122, "Data Forms Validation");
        XEP_NAMES.put(123, "Entity Metadata");
        XEP_NAMES.put(124, "Bidirectional-streams Over Synchronous HTTP (BOSH)");
        XEP_NAMES.put(125, "vCard Infobits Mapping");
        XEP_NAMES.put(126, "Invisibility");
        XEP_NAMES.put(127, "Common Alerting Protocol (CAP) Over XMPP");
        XEP_NAMES.put(128, "Service Discovery Extensions");
        XEP_NAMES.put(129, "WebDAV File Transfers");
        XEP_NAMES.put(130, "Waiting Lists");
        XEP_NAMES.put(131, "Stanza Headers and Internet Metadata");
        XEP_NAMES.put(132, "Presence Obtained via Kinesthetic Excitation (POKE)");
        XEP_NAMES.put(133, "Service Administration");
        XEP_NAMES.put(134, "XMPP Design Guidelines");
        XEP_NAMES.put(135, "File Sharing");
        XEP_NAMES.put(136, "Message Archiving");
        XEP_NAMES.put(137, "Publishing Stream Initiation Requests");
        XEP_NAMES.put(138, "Stream Compression");
        XEP_NAMES.put(139, "Security SIG");
        XEP_NAMES.put(140, "Shared Groups");
        XEP_NAMES.put(141, "Data Forms Layout");
        XEP_NAMES.put(142, "Workgroup Queues");
        XEP_NAMES.put(143, "Guidelines for Authors of XMPP Extension Protocols");
        XEP_NAMES.put(144, "Roster Item Exchange");
        XEP_NAMES.put(145, "Annotations");
        XEP_NAMES.put(146, "Remote Controlling Clients");
        XEP_NAMES.put(147, "XMPP URI Scheme Query Components");
        XEP_NAMES.put(148, "Instant Messaging Intelligence Quotient (IM IQ)");
        XEP_NAMES.put(149, "Time Periods");
        XEP_NAMES.put(150, "Use of Entity Tags in XMPP Extensions");
        XEP_NAMES.put(151, "Virtual Presence");
        XEP_NAMES.put(152, "Reachability Addresses");
        XEP_NAMES.put(153, "vCard-Based Avatars");
        XEP_NAMES.put(154, "User Profile");
        XEP_NAMES.put(155, "Stanza Session Negotiation");
        XEP_NAMES.put(156, "Discovering Alternative XMPP Connection Methods");
        XEP_NAMES.put(157, "Contact Addresses for XMPP Services");
        XEP_NAMES.put(158, "CAPTCHA Forms");
        XEP_NAMES.put(159, "Spim-Blocking Control");
        XEP_NAMES.put(160, "Best Practices for Handling Offline Messages");
        XEP_NAMES.put(161, "Abuse Reporting");
        XEP_NAMES.put(162, "Best Practices for Roster and Subscription Management");
        XEP_NAMES.put(163, "Personal Eventing Protocol");
        XEP_NAMES.put(164, "vCard Filtering");
        XEP_NAMES.put(165, "Best Practices to Discourage JID Mimicking");
        XEP_NAMES.put(166, "Jingle");
        XEP_NAMES.put(167, "Jingle RTP Sessions");
        XEP_NAMES.put(168, "Resource Application Priority");
        XEP_NAMES.put(169, "Twas The Night Before Christmas (Jabber Version)");
        XEP_NAMES.put(170, "Recommended Order of Stream Feature Negotiation");
        XEP_NAMES.put(171, "Language Translation");
        XEP_NAMES.put(172, "User Nickname");
        XEP_NAMES.put(173, "Pubsub Subscription Storage");
        XEP_NAMES.put(174, "Serverless Messaging");
        XEP_NAMES.put(175, "Best Practices for Use of SASL ANONYMOUS");
        XEP_NAMES.put(176, "Jingle ICE-UDP Transport Method");
        XEP_NAMES.put(177, "Jingle Raw UDP Transport Method");
        XEP_NAMES.put(178, "Best Practices for Use of SASL EXTERNAL with Certificates");
        XEP_NAMES.put(179, "Jingle IAX Transport Method");
        XEP_NAMES.put(180, "Jingle Video via RTP");
        XEP_NAMES.put(181, "Jingle DTMF");
        XEP_NAMES.put(182, "Application-Specific Error Conditions");
        XEP_NAMES.put(183, "Jingle Telepathy Transport");
        XEP_NAMES.put(184, "Message Delivery Receipts");
        XEP_NAMES.put(185, "Dialback Key Generation and Validation");
        XEP_NAMES.put(186, "Invisible Command");
        XEP_NAMES.put(187, "Offline Encrypted Sessions");
        XEP_NAMES.put(188, "Cryptographic Design of Encrypted Sessions");
        XEP_NAMES.put(189, "Public Key Publishing");
        XEP_NAMES.put(190, "Best Practice for Closing Idle Streams");
        XEP_NAMES.put(191, "Blocking Command");
        XEP_NAMES.put(192, "Proposed Stream Feature Improvements");
        XEP_NAMES.put(193, "Proposed Resource Binding Improvements");
        XEP_NAMES.put(194, "User Chatting");
        XEP_NAMES.put(195, "User Browsing");
        XEP_NAMES.put(196, "User Gaming");
        XEP_NAMES.put(197, "User Viewing");
        XEP_NAMES.put(198, "Stream Management");
        XEP_NAMES.put(199, "XMPP Ping");
        XEP_NAMES.put(200, "Stanza Encryption");
        XEP_NAMES.put(201, "Best Practices for Message Threads");
        XEP_NAMES.put(202, "Entity Time");
        XEP_NAMES.put(203, "Delayed Delivery");
        XEP_NAMES.put(204, "Collaborative Data Objects");
        XEP_NAMES.put(205, "Best Practices to Discourage Denial of Service Attacks");
        XEP_NAMES.put(206, "XMPP Over BOSH");
        XEP_NAMES.put(207, "XMPP Eventing via Pubsub");
        XEP_NAMES.put(208, "Bootstrapping Implementation of Jingle");
        XEP_NAMES.put(209, "Metacontacts");
        XEP_NAMES.put(210, "Requirements for Encrypted Sessions");
        XEP_NAMES.put(211, "XMPP Basic Client 2008");
        XEP_NAMES.put(212, "XMPP Basic Server 2008");
        XEP_NAMES.put(213, "XMPP Intermediate IM Client 2008");
        XEP_NAMES.put(214, "File Repository and Sharing");
        XEP_NAMES.put(215, "External Service Discovery");
        XEP_NAMES.put(216, "XMPP Intermediate IM Server 2008");
        XEP_NAMES.put(217, "Simplified Encrypted Session Negotiation");
        XEP_NAMES.put(218, "Bootstrapping Implementation of Encrypted Sessions");
        XEP_NAMES.put(219, "Hop Check");
        XEP_NAMES.put(220, "Server Dialback");
        XEP_NAMES.put(221, "Data Forms Media Element");
        XEP_NAMES.put(222, "Persistent Storage of Public Data via PubSub");
        XEP_NAMES.put(223, "Persistent Storage of Private Data via PubSub");
        XEP_NAMES.put(224, "Attention");
        XEP_NAMES.put(225, "Component Connections");
        XEP_NAMES.put(226, "Message Stanza Profiles");
        XEP_NAMES.put(227, "Portable Import/Export Format for XMPP-IM Servers");
        XEP_NAMES.put(228, "Requirements for Shared Editing");
        XEP_NAMES.put(229, "Stream Compression with LZW");
        XEP_NAMES.put(230, "Service Discovery Notifications");
        XEP_NAMES.put(231, "Bits of Binary");
        XEP_NAMES.put(232, "Software Information");
        XEP_NAMES.put(233, "XMPP Server Registration for use with Kerberos V5");
        XEP_NAMES.put(234, "Jingle File Transfer");
        XEP_NAMES.put(235, "OAuth Over XMPP");
        XEP_NAMES.put(236, "Abuse Reporting");
        XEP_NAMES.put(237, "Roster Versioning");
        XEP_NAMES.put(238, "XMPP Protocol Flows for Inter-Domain Federation");
        XEP_NAMES.put(239, "Binary XMPP");
        XEP_NAMES.put(240, "Auto-Discovery of JabberIDs");
        XEP_NAMES.put(241, "Encryption of Archived Messages");
        XEP_NAMES.put(242, "XMPP Client Compliance 2009");
        XEP_NAMES.put(243, "XMPP Server Compliance 2009");
        XEP_NAMES.put(244, "IO Data");
        XEP_NAMES.put(245, "The /me Command");
        XEP_NAMES.put(246, "End-to-End XML Streams");
        XEP_NAMES.put(247, "Jingle XML Streams");
        XEP_NAMES.put(248, "PubSub Collection Nodes");
        XEP_NAMES.put(249, "Direct MUC Invitations");
        XEP_NAMES.put(250, "C2C Authentication Using TLS");
        XEP_NAMES.put(251, "Jingle Session Transfer");
        XEP_NAMES.put(252, "BOSH Script Syntax");
        XEP_NAMES.put(253, "PubSub Chaining");
        XEP_NAMES.put(254, "PubSub Queueing");
        XEP_NAMES.put(255, "Location Query");
        XEP_NAMES.put(256, "Last Activity in Presence");
        XEP_NAMES.put(257, "Client Certificate Management for SASL EXTERNAL");
        XEP_NAMES.put(258, "Security Labels in XMPP");
        XEP_NAMES.put(259, "Message Mine-ing");
        XEP_NAMES.put(260, "Jingle SOCKS5 Bytestreams Transport Method");
        XEP_NAMES.put(261, "Jingle In-Band Bytestreams Transport Method");
        XEP_NAMES.put(262, "Use of ZRTP in Jingle RTP Sessions");
        XEP_NAMES.put(263, "ECO-XMPP");
        XEP_NAMES.put(264, "Jingle Content Thumbnails");
        XEP_NAMES.put(265, "Out-of-Band Stream Data");
        XEP_NAMES.put(266, "Codecs for Jingle Audio");
        XEP_NAMES.put(267, "Server Buddies");
        XEP_NAMES.put(268, "Incident Handling");
        XEP_NAMES.put(269, "Jingle Early Media");
        XEP_NAMES.put(270, "XMPP Compliance Suites 2010");
        XEP_NAMES.put(271, "XMPP Nodes");
        XEP_NAMES.put(272, "Multiparty Jingle (Muji)");
        XEP_NAMES.put(273, "Stanza Interception and Filtering Technology (SIFT)");
        XEP_NAMES.put(274, "Design Considerations for Digital Signatures in XMPP");
        XEP_NAMES.put(275, "Entity Reputation");
        XEP_NAMES.put(276, "Presence Decloaking");
        XEP_NAMES.put(277, "Microblogging over XMPP");
        XEP_NAMES.put(278, "Jingle Relay Nodes");
        XEP_NAMES.put(279, "Server IP Check");
        XEP_NAMES.put(280, "Message Carbons");
        XEP_NAMES.put(281, "DMUC1: Distributed Multi-User Chat");
        XEP_NAMES.put(282, "DMUC2: Distributed MUC");
        XEP_NAMES.put(283, "Moved");
        XEP_NAMES.put(284, "Shared XML Editing");
        XEP_NAMES.put(285, "Encapsulating Digital Signatures in XMPP");
        XEP_NAMES.put(286, "Mobile Considerations");
        XEP_NAMES.put(287, "Spim Markers and Reports");
        XEP_NAMES.put(288, "Bidirectional Server-to-Server Connections");
        XEP_NAMES.put(289, "Federated MUC for Constrained Environments");
        XEP_NAMES.put(290, "Encapsulated Digital Signatures in XMPP");
        XEP_NAMES.put(291, "Service Delegation");
        XEP_NAMES.put(292, "vCard4 Over XMPP");
        XEP_NAMES.put(293, "Jingle RTP Feedback Negotiation");
        XEP_NAMES.put(294, "Jingle RTP Header Extensions Negotiation");
        XEP_NAMES.put(295, "JSON Encodings for XMPP");
        XEP_NAMES.put(296, "Best Practices for Resource Locking");
        XEP_NAMES.put(297, "Stanza Forwarding");
        XEP_NAMES.put(298, "Delivering Conference Information to Jingle Participants (Coin)");
        XEP_NAMES.put(299, "Codecs for Jingle Video");
        XEP_NAMES.put(300, "Use of Cryptographic Hash Functions in XMPP");
        XEP_NAMES.put(301, "In-Band Real Time Text");
        XEP_NAMES.put(302, "XMPP Compliance Suites 2012");
        XEP_NAMES.put(303, "Commenting");
        XEP_NAMES.put(304, "Whitespace Keepalive Negotiation");
        XEP_NAMES.put(305, "XMPP Quickstart");
        XEP_NAMES.put(306, "Extensible Status Conditions for Multi-User Chat");
        XEP_NAMES.put(307, "Unique Room Names for Multi-User Chat");
        XEP_NAMES.put(308, "Last Message Correction");
        XEP_NAMES.put(309, "Service Directories");
        XEP_NAMES.put(310, "Presence State Annotations");
        XEP_NAMES.put(311, "MUC Fast Reconnect");
        XEP_NAMES.put(312, "PubSub Since");
        XEP_NAMES.put(313, "Message Archive Management");
        XEP_NAMES.put(314, "Security Labels in PubSub");
        XEP_NAMES.put(315, "Data Forms XML Element");
        XEP_NAMES.put(316, "MUC Eventing Protocol");
        XEP_NAMES.put(317, "Hats");
        XEP_NAMES.put(318, "Best Practices for Client Initiated Presence Probes");
        XEP_NAMES.put(319, "Last User Interaction in Presence");
        XEP_NAMES.put(320, "Use of DTLS-SRTP in Jingle Sessions");
        XEP_NAMES.put(321, "Remote Roster Management");
        XEP_NAMES.put(322, "Efficient XML Interchange (EXI) Format");
        XEP_NAMES.put(323, "Internet of Things - Sensor Data");
        XEP_NAMES.put(324, "Internet of Things - Provisioning");
        XEP_NAMES.put(325, "Internet of Things - Control");
        XEP_NAMES.put(326, "Internet of Things - Concentrators");
        XEP_NAMES.put(327, "Rayo");
        XEP_NAMES.put(328, "JID Prep");
        XEP_NAMES.put(329, "File Information Sharing");
        XEP_NAMES.put(330, "Pubsub Subscription");
        XEP_NAMES.put(331, "Data Forms - Color Field Types");
        XEP_NAMES.put(332, "HTTP over XMPP transport");
        XEP_NAMES.put(333, "Chat Markers");
        XEP_NAMES.put(334, "Message Processing Hints");
        XEP_NAMES.put(335, "JSON Containers");
        XEP_NAMES.put(336, "Data Forms - Dynamic Forms");
        XEP_NAMES.put(337, "Event Logging over XMPP");
        XEP_NAMES.put(338, "Jingle Grouping Framework");
        XEP_NAMES.put(339, "Source-Specific Media Attributes in Jingle");
        XEP_NAMES.put(340, "COnferences with LIghtweight BRIdging (COLIBRI)");
        XEP_NAMES.put(341, "Rayo CPA");
        XEP_NAMES.put(342, "Rayo Fax");
        XEP_NAMES.put(343, "Signaling WebRTC datachannels in Jingle");
        XEP_NAMES.put(344, "Impact of TLS and DNSSEC on Dialback");
        XEP_NAMES.put(345, "Form of Membership Applications");
        XEP_NAMES.put(346, "Form Discovery and Publishing");
        XEP_NAMES.put(347, "Internet of Things - Discovery");
        XEP_NAMES.put(348, "Signing Forms");
        XEP_NAMES.put(349, "Rayo Clustering");
        XEP_NAMES.put(350, "Data Forms Geolocation Element");
        XEP_NAMES.put(351, "Recipient Server Side Notifications Filtering");
        XEP_NAMES.put(352, "Client State Indication");
        XEP_NAMES.put(353, "Jingle Message Initiation");
        XEP_NAMES.put(354, "Customizable Message Routing");
        XEP_NAMES.put(355, "Namespace Delegation");
        XEP_NAMES.put(356, "Privileged Entity");
        XEP_NAMES.put(357, "Push Notifications");
        XEP_NAMES.put(358, "Publishing Available Jingle Sessions");
        XEP_NAMES.put(359, "Unique and Stable Stanza IDs");
        XEP_NAMES.put(360, "Nonzas (are not Stanzas)");
        XEP_NAMES.put(361, "Zero Handshake Server to Server Protocol");
        XEP_NAMES.put(362, "Raft over XMPP");
        XEP_NAMES.put(363, "HTTP File Upload");
        XEP_NAMES.put(364, "Current Off-the-Record Messaging Usage");
        XEP_NAMES.put(365, "Server to Server communication over STANAG 5066 ARQ");
        XEP_NAMES.put(366, "Entity Versioning");
        XEP_NAMES.put(367, "Message Attaching");
        XEP_NAMES.put(368, "SRV records for XMPP over TLS");
        XEP_NAMES.put(369, "Mediated Information eXchange (MIX)");
        XEP_NAMES.put(370, "Jingle HTTP Transport Method");
        XEP_NAMES.put(371, "Jingle ICE Transport Method");
        XEP_NAMES.put(372, "References");
    }
}
